super_agents:
  version: 1.0.0
  methodology:
    workflow_type: agile-ai
    default_agents:
      - analyst
      - pm
      - architect
      - developer
      - qa
    quality_gates: true
  ai:
    providers:
      primary: anthropic
      fallback: openai
      research: perplexity
    models:
      analyst: claude-3-5-sonnet
      architect: claude-3-5-sonnet
      developer: claude-3-5-sonnet
      qa: gpt-4o
      pm: claude-3-5-sonnet
      scrum_master: claude-3-5-sonnet
      product_owner: claude-3-5-sonnet
      ux_expert: claude-3-5-sonnet
      bmad_master: claude-3-5-sonnet
      bmad_orchestrator: claude-3-5-sonnet
  integrations:
    mcp_enabled: false
    cli_enabled: true
  workspace:
    docs_dir: docs/
    tasks_dir: .super-agents/tasks/
    state_file: .super-agents/state.json
  project:
    name: super-agents
    type: fullstack
    initialized: true
    created_at: 2025-07-30T23:29:09.046Z
