name: daily-health-check
description: Daily system health check and status report
version: 1.0.0
created: '2025-07-30T19:29:04.575Z'
trigger: scheduled
steps:
  - type: command
    name: System Status Check
    command: sa doctor --verbose
  - type: sa-tool
    name: List Active Tasks
    tool: task list --status=active
  - type: notification
    name: Send Daily Report
    message: Daily health check completed
    channel: console
environment: {}
notifications: {}
